### ISSUE TITLE
Test suite error testing with Bundler 1.13.6

### ISSUE THREAD

**Issue by voxik** [bundlerext/bundler_ext#20]
After update of Bundler in Fedora to 1.13.6 version, bundler_ext test suite started to fail in Koschei [1] with following message:

```
  1) BundlerExt::Runtime#bundler returns handle to bundler runtime
     Failure/Error: bundler.root.to_s.should == File.expand_path('spec/fixtures')
     NoMethodError:
       undefined method `root' for #<Bundler::Runtime:0x581f4868>
     # ./spec/bundler_ext/runtime_spec.rb:34:in `block (3 levels) in <module:BundlerExt>'
```

[1] https://apps.fedoraproject.org/koschei/package/rubygem-bundler_ext?collection=f26

**Comment by domcleal** [comment]
Bundler::Runtime (since 1.13) no longer extends Environment and loses the attr_reader this example relied on. Perhaps either:

1. Remove the check for bundler.root
1. Change it to check the instance variable
1. Use rspec expectations to check the root is passed into the Bundler::Runtime constructor
1. Send a patch to Bundler to add the reader back

**Comment by movitto** [comment]
@domcleal @voxik yes it seems the first option is optimal since that feature was removed from bundler. We'd just have to remove that line in the spec.

I can send a PR / update the gem as soon as I get the spec suite working locally.

**Comment by voxik** [comment]
Interesting, this error disappeared with Bundler 1.16.0:

https://apps.fedoraproject.org/koschei/package/rubygem-bundler_ext?collection=f28
