### PR TITLE
Update to rspec 3 and add CI

### LINKED ISSUE #6: Add travis configuration (and probably Gemfile)

### LINKED ISSUE #20: Test suite error testing with Bundler 1.13.6
After update of Bundler in Fedora to 1.13.6 version, bundler_ext test suite started to fail in Koschei [1] with following message:

```
  1) BundlerExt::Runtime#bundler returns handle to bundler runtime
     Failure/Error: bundler.root.to_s.should == File.expand_path('spec/fixtures')
     NoMethodError:
       undefined method `root' for #<Bundler::Runtime:0x581f4868>
     # ./spec/bundler_ext/runtime_spec.rb:34:in `block (3 levels) in <module:BundlerExt>'
```

[1] https://apps.fedoraproject.org/koschei/package/rubygem-bundler_ext?collection=f26

### PR DESCRIPTION
**Pull request by ekohl**
Fixes #6, Fixes #20

### CODE REVIEW

**Comment by ekohl** [comment]
CI run that's green: https://github.com/ekohl/bundler_ext/actions/runs/2656710928
